---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)

library(p8105.datasets)
```

```{r}
data("rest_inspec")

restaurant_data =
  rest_inspec |> 
  filter(
    !is.na(score),
    !is.na(boro),
    boro != "0"
  ) |> 
  sample_n(3000) |> 
  select(
    boro, cuisine_description, score, inspection_date
  )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
restaurant_data |> 
  plot_ly(
    x = ~boro, y = ~score, color = ~boro,
    type = "box"
  )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
restaurant_data |> 
  count(cuisine_description) |> 
  arrange(desc(n)) |> 
  head(10) |> 
  plot_ly(
    x = ~n, y = ~cuisine_description,
    type = "bar", orientation = "h"
  )
```

### Chart C

```{r}
restaurant_data |> 
  plot_ly(
    x = ~score,
    type = "histogram"
  )
```

